--
-- Yet another oracle-sql-calendar-query
-- How Good Am I in SQL? Only this much..
-- Venkata Bhattaram / Tinitiate.com
-- Prints the Month Calender
-- 
select decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',0,
         'MONDAY',-1,
         'TUESDAY',-2,
         'WEDNESDAY',-3,
         'THURSDAY',-4,
         'FRIDAY',-5,
         'SATURDAY',-6)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',0,
         'MONDAY',-1,
         'TUESDAY',-2,
         'WEDNESDAY',-3,
         'THURSDAY',-4,
         'FRIDAY',-5,
         'SATURDAY',-6)+(level-1)*7,'DD')
         ,'')
         SUNDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',1,
         'MONDAY',0,
         'TUESDAY',-1,
         'WEDNESDAY',-2,
         'THURSDAY',-3,
         'FRIDAY',-4,
         'SATURDAY',-5)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',1,
         'MONDAY',0,
         'TUESDAY',-1,
         'WEDNESDAY',-2,
         'THURSDAY',-3,
         'FRIDAY',-4,
         'SATURDAY',-5)+(level-1)*7,'DD')
         ,'')
         MONDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',2,
         'MONDAY',1,
         'TUESDAY',0,
         'WEDNESDAY',-1,
         'THURSDAY',-2,
         'FRIDAY',-3,
         'SATURDAY',-4)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',2,
         'MONDAY',1,
         'TUESDAY',0,
         'WEDNESDAY',-1,
         'THURSDAY',-2,
         'FRIDAY',-3,
         'SATURDAY',-4)+(level-1)*7,'DD')
         ,'')
         TUESDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',3,
         'MONDAY',2,
         'TUESDAY',1,
         'WEDNESDAY',0,
         'THURSDAY',-1,
         'FRIDAY',-2,
         'SATURDAY',3)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',3,
         'MONDAY',2,
         'TUESDAY',1,
         'WEDNESDAY',0,
         'THURSDAY',-1,
         'FRIDAY',-2,
         'SATURDAY',3)+(level-1)*7,'DD')
         ,'')
         WEDNESDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',0,
         'MONDAY',1,
         'TUESDAY',2,
         'WEDNESDAY',3,
         'THURSDAY',0,
         'FRIDAY',-1,
         'SATURDAY',-2)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',0,
         'MONDAY',1,
         'TUESDAY',2,
         'WEDNESDAY',3,
         'THURSDAY',0,
         'FRIDAY',-1,
         'SATURDAY',-2)+(level-1)*7,'DD')
         ,'')
         THURSDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',5,
         'MONDAY',4,
         'TUESDAY',3,
         'WEDNESDAY',2,
         'THURSDAY',1,
         'FRIDAY',0,
         'SATURDAY',-1)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',5,
         'MONDAY',4,
         'TUESDAY',3,
         'WEDNESDAY',2,
         'THURSDAY',1,
         'FRIDAY',0,
         'SATURDAY',-1)+(level-1)*7,'DD')
         ,'')
         FRIDAY,
         decode(
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',6,
         'MONDAY',5,
         'TUESDAY',4,
         'WEDNESDAY',3,
         'THURSDAY',2,
         'FRIDAY',1,
         'SATURDAY',0)+(level-1)*7,'MON')
         ,trim(to_char(sysdate,'MON')),
         to_char(
         to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY')+
         decode(trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
         'SUNDAY',6,
         'MONDAY',5,
         'TUESDAY',4,
         'WEDNESDAY',3,
         'THURSDAY',2,
         'FRIDAY',1,
         'SATURDAY',0)+(level-1)*7,'DD')
         ,'')
         SATURDAY
from dual
connect by level <=(decode(
trim(to_char(to_date('01'||to_char(sysdate,'MMYYYY'),'DDMMYYYY'),'DAY')),
'SATURDAY',decode(to_char(last_day(sysdate),'DD'),31,6,30,6,5),
5)
);
